### ISSUE TITLE
project/repo description

### ISSUE THREAD

**Issue by matanster** [microsoft/mwt-ds#124]
a Vimeo from the 2017 ICLR Tutorial session seems to imply this repo is all it takes for the Decision Service.

![image](https://user-images.githubusercontent.com/4996067/43048646-adfad854-8df3-11e8-8477-60bf49e76d19.png)

However the repo's tagline sounds much more reserved. Would you care to clarify regarding the fine scope of this repository?

**Comment by matanster** [comment]
Also, care to include the relation to Vowpal Wabbit? 
Does this repo implement its own CB algo? does it assume a VW learner is deployed by its user? some other relation?

**Comment by JohnLangford** [comment]
This one is an early version of the overall decision service.  It's since
matured---most of the code is in the VW repository currently and new loops
can be created off of http://ds.microsoft.com.

-John
