### ISSUE TITLE
Output policy arguments from hyper parameter sweep should not contain --dsjson in it

### ISSUE THREAD

**Issue by sharathmalladi** [microsoft/mwt-ds#148]
Since we don't expect custom policies to have dsjson in the policy arguments, we don't want to output policies that have the dsjson in the policy arguments as well.

**Comment by marco-rossi29** [comment]
Can you specify what your definition of `Output policy arguments from hyper parameter sweep` is? In particular, can you post a link to a line?

**Comment by sharathmalladi** [comment]
I was refering to this line of code: https://github.com/microsoft/mwt-ds/blob/master/DataScience/Experimentation.py#L210

When the offline experimentation results are saved, the output policies also list "--dsjson" in them. We don't want this argument being output since it is not really a ML argument.

**Comment by marco-rossi29** [comment]
Then I don't agree with this issue: Experimentation.py is looking for the best VW command and --dsjson must be part of such command, otherwise VW wouldn't work
