### ISSUE TITLE
fresh build fails

### ISSUE THREAD

**Issue by danmelamed** [Microsoft/mwt-ds#19]
I set my build config to debug/x64, but...

Error		Metadata file 'C:\dev\Repos\mwt-ds\bin\x64\Debug\Microsoft.Research.MultiWorldTesting.ClientLibrary.dll' could not be found	DecisionServicePrivateWeb	C:\dev\Repos\mwt-ds\mc\CSC		
Error		Metadata file 'C:\dev\Repos\mwt-ds\bin\x64\Debug\Microsoft.Research.MultiWorldTesting.JoinUploader.dll' could not be found	ds-provisioning	C:\dev\Repos\mwt-ds\provisioning\test\CSC		
Error		Metadata file 'C:\dev\Repos\mwt-ds\bin\x64\Debug\Microsoft.Research.MultiWorldTesting.ClientLibrary.dll' could not be found	ds-provisioning	C:\dev\Repos\mwt-ds\provisioning\test\CSC

**Comment by eisber** [comment]
Build again

**Comment by lhoang29** [comment]
It works for me. Maybe local build is messed up?

**Comment by danmelamed** [comment]
When I build again, I get

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'INumberOfActionsProvider<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWJson.cs	33	Active
Error	CS0234	The type or namespace name 'Contract' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionService.cs	2	Active
Error	CS0234	The type or namespace name 'ExploreLibrary' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionService.cs	3	Active
Error	CS0246	The type or namespace name 'ApplicationClientMetadata' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionService.cs	13	Active
Error	CS0246	The type or namespace name 'ApplicationClientMetadata' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionService.cs	13	Active
Error	CS0246	The type or namespace name 'ApplicationClientMetadata' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionService.cs	27	Active
Error	CS0246	The type or namespace name 'ApplicationClientMetadata' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionService.cs	35	Active
Error	CS0234	The type or namespace name 'ExploreLibrary' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionService.UntilModelReady.cs	1	Active
Error	CS0246	The type or namespace name 'IContextMapper<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionService.UntilModelReady.cs	11	Active
Error	CS0246	The type or namespace name 'ActionProbability' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionService.UntilModelReady.cs	11	Active
Error	CS0234	The type or namespace name 'Contract' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	1	Active
Error	CS0234	The type or namespace name 'ExploreLibrary' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	2	Active
Error	CS0246	The type or namespace name 'IContextMapper<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	20	Active
Error	CS0246	The type or namespace name 'ActionProbability' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	20	Active
Error	CS0246	The type or namespace name 'IRecorder<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	22	Active
Error	CS0246	The type or namespace name 'IContextMapper<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	24	Active
Error	CS0246	The type or namespace name 'ActionProbability' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	24	Active
Error	CS0246	The type or namespace name 'ApplicationClientMetadata' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	26	Active
Error	CS0246	The type or namespace name 'MwtExplorer<,,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	27	Active
Error	CS0246	The type or namespace name 'ActionProbability' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	27	Active
Error	CS0246	The type or namespace name 'INumberOfActionsProvider<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	30	Active
Error	CS0246	The type or namespace name 'IRecorder<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	32	Active
Error	CS0246	The type or namespace name 'ApplicationClientMetadata' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	42	Active
Error	CS0246	The type or namespace name 'IContextMapper<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	43	Active
Error	CS0246	The type or namespace name 'ActionProbability' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	43	Active
Error	CS0246	The type or namespace name 'IContextMapper<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	44	Active
Error	CS0246	The type or namespace name 'ActionProbability' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	44	Active
Error	CS0246	The type or namespace name 'IFullExplorer<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	45	Active
Error	CS0246	The type or namespace name 'IInitialExplorer<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	46	Active
Error	CS0246	The type or namespace name 'ActionProbability' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	46	Active
Error	CS0246	The type or namespace name 'IExplorer<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	226	Active
Error	CS0246	The type or namespace name 'ActionProbability' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	226	Active
Error	CS0246	The type or namespace name 'IContextMapper<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	232	Active
Error	CS0246	The type or namespace name 'ActionProbability' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	232	Active
Error	CS0246	The type or namespace name 'IRecorder<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	238	Active
Error	CS0246	The type or namespace name 'IRecorder<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	252	Active
Error	CS0246	The type or namespace name 'IPolicy<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	258	Active
Error	CS0246	The type or namespace name 'IRanker<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	286	Active
Error	CS0246	The type or namespace name 'INumberOfActionsProvider<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceClient.cs	382	Active
Error	CS0234	The type or namespace name 'JoinUploader' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceConfiguration.cs	3	Active
Error	CS0246	The type or namespace name 'BatchingConfiguration' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceConfiguration.cs	72	Active
Error	CS0246	The type or namespace name 'BatchingConfiguration' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceConfiguration.cs	88	Active
Error	CS0246	The type or namespace name 'BatchingConfiguration' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceConfiguration.cs	167	Active
Error	CS0234	The type or namespace name 'ExploreLibrary' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\DecisionServiceStaticClient.cs	1	Active
Error	CS0234	The type or namespace name 'ExploreLibrary' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\ILogger.cs	3	Active
Error	CS0234	The type or namespace name 'JoinUploader' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\JoinServiceLogger.cs	1	Active
Error	CS0234	The type or namespace name 'ExploreLibrary' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\JoinServiceLogger.cs	2	Active
Error	CS0246	The type or namespace name 'IRecorder<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\JoinServiceLogger.cs	10	Active
Error	CS0246	The type or namespace name 'IEventUploader' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\JoinServiceLogger.cs	14	Active
Error	CS0246	The type or namespace name 'IEventUploader' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\JoinServiceLogger.cs	15	Active
Error	CS0246	The type or namespace name 'BatchingConfiguration' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\JoinServiceLogger.cs	29	Active
Error	CS0246	The type or namespace name 'BatchingConfiguration' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\JoinServiceLogger.cs	40	Active
Error	CS0246	The type or namespace name 'BatchingConfiguration' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\JoinServiceLogger.cs	41	Active
Error	CS0234	The type or namespace name 'ExploreLibrary' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWBaseContextMapper.cs	1	Active
Error	CS0246	The type or namespace name 'IUpdatable<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWBaseContextMapper.cs	10	Active
Error	CS0246	The type or namespace name 'IContextMapper<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWBaseContextMapper.cs	10	Active
Error	CS0246	The type or namespace name 'PolicyDecision<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWBaseContextMapper.cs	87	Active
Error	CS0246	The type or namespace name 'PolicyDecision<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWBaseContextMapper.cs	101	Active
Error	CS0234	The type or namespace name 'ExploreLibrary' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWExplorer.cs	1	Active
Error	CS0246	The type or namespace name 'ActionProbability' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWExplorer.cs	15	Active
Error	CS0246	The type or namespace name 'IContextMapper<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWExplorer.cs	16	Active
Error	CS0246	The type or namespace name 'ActionProbability' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWExplorer.cs	16	Active
Error	CS0246	The type or namespace name 'INumberOfActionsProvider<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWExplorer.cs	16	Active
Error	CS0246	The type or namespace name 'PolicyDecision<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWExplorer.cs	38	Active
Error	CS0246	The type or namespace name 'ActionProbability' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWExplorer.cs	38	Active
Error	CS0234	The type or namespace name 'ExploreLibrary' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWJson.cs	1	Active
Error	CS0246	The type or namespace name 'IPolicy<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWJson.cs	11	Active
Error	CS0246	The type or namespace name 'PolicyDecision<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWJson.cs	18	Active
Error	CS0246	The type or namespace name 'IRanker<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWJson.cs	33	Active
Error	CS0246	The type or namespace name 'PolicyDecision<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWJson.cs	40	Active
Error	CS0234	The type or namespace name 'ExploreLibrary' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWJsonExplorer.cs	1	Active
Error	CS0246	The type or namespace name 'ActionProbability' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWJsonExplorer.cs	15	Active
Error	CS0246	The type or namespace name 'IContextMapper<,>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWJsonExplorer.cs	16	Active
Error	CS0246	The type or namespace name 'ActionProbability' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWJsonExplorer.cs	16	Active
Error	CS0246	The type or namespace name 'INumberOfActionsProvider<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWJsonExplorer.cs	16	Active
Error	CS0246	The type or namespace name 'PolicyDecision<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWJsonExplorer.cs	23	Active
Error	CS0246	The type or namespace name 'ActionProbability' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWJsonExplorer.cs	23	Active
Error	CS0234	The type or namespace name 'ExploreLibrary' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWPolicy.cs	1	Active
Error	CS0246	The type or namespace name 'IPolicy<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWPolicy.cs	10	Active
Error	CS0246	The type or namespace name 'PolicyDecision<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWPolicy.cs	21	Active
Error	CS0234	The type or namespace name 'ExploreLibrary' does not exist in the namespace 'Microsoft.Research.MultiWorldTesting' (are you missing an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWRanker.cs	1	Active
Error	CS0246	The type or namespace name 'IRanker<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWRanker.cs	14	Active
Error	CS0246	The type or namespace name 'INumberOfActionsProvider<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWRanker.cs	14	Active
Error	CS0246	The type or namespace name 'PolicyDecision<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWRanker.cs	33	Active
Error	CS0246	The type or namespace name 'IRanker<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWRanker.cs	60	Active
Error	CS0246	The type or namespace name 'INumberOfActionsProvider<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWRanker.cs	60	Active
Error	CS0246	The type or namespace name 'PolicyDecision<>' could not be found (are you missing a using directive or an assembly reference?)	ClientDecisionService	C:\dev\Repos\mwt-ds\client\ClientDecisionService\VW\VWRanker.cs	78	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ApplicationBlobConstants'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationBlobConstants.cs	9	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ApplicationBlobConstants.ModelContainerName'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationBlobConstants.cs	12	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ApplicationBlobConstants.LatestModelBlobName'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationBlobConstants.cs	13	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ApplicationBlobConstants.SettingsContainerName'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationBlobConstants.cs	16	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ApplicationBlobConstants.LatestClientSettingsBlobName'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationBlobConstants.cs	17	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ApplicationBlobConstants.LatestTrainerSettingsBlobName'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationBlobConstants.cs	18	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ApplicationBlobConstants.LatestExtraSettingsBlobName'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationBlobConstants.cs	19	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ApplicationBlobConstants.OfflineEvalContainerName'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationBlobConstants.cs	21	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ApplicationMetadataUtil'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationMetadataUtil.cs	8	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ApplicationMetadataUtil.DownloadMetadata<TMetadata>(string)'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationMetadataUtil.cs	10	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ApplicationSettingConstants'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationSettingConstants.cs	9	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ApplicationSettingConstants.UseLatestModelSetting'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationSettingConstants.cs	11	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'TrainFrequency.Low'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationTransferMetadata.cs	30	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'TrainFrequency.High'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationTransferMetadata.cs	31	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ApplicationClientMetadata'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationTransferMetadata.cs	34	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ApplicationClientMetadata.InitialExplorationEpsilon'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationTransferMetadata.cs	71	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ApplicationExtraMetadata'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ApplicationTransferMetadata.cs	74	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ServiceConstants'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ServiceConstants.cs	9	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ServiceConstants.JoinAddress'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ServiceConstants.cs	12	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ServiceConstants.JoinPostAddress'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ServiceConstants.cs	13	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ServiceConstants.TokenAuthenticationScheme'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ServiceConstants.cs	14	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ServiceConstants.ConnectionStringAuthenticationScheme'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ServiceConstants.cs	15	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ServiceConstants.IncompleteContainerPrefix'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ServiceConstants.cs	17	Active
Warning	CS1591	Missing XML comment for publicly visible type or member 'ServiceConstants.JoinedBlobContainerPrefix'	MultiWorldTestingServiceContract	C:\dev\Repos\mwt-ds\client\MultiWorldTestingServiceContract\ServiceConstants.cs	18	Active
Warning		Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.	ds-provisioning

**Comment by danmelamed** [comment]
Dependency tracking could be improved, but I'm removing the R0 milestone since it's not urgent.
