### ISSUE TITLE
Strange warning

### ISSUE THREAD

**Issue by JohnLangford** [Microsoft/mwt-ds#2]
When you "Deploy to Azure" then wait around for several minutes, the bell shows a message: "RunFinished 
in data factory dsdatafactory1458774893, validation for table joined-examples slice start time... finished at ... "

What does this mean?  And where does it come from?

**Comment by lhoang29** [comment]
The portal produces messages about resources that are not related to the DS as well. You can generally ignore these. That reminds me though that we'll need to make a pass through to clean up the unused items.

**Comment by lhoang29** [comment]
Going to close this since it's not related to DS.

**Comment by sidsen** [comment]
Yes, please keep an issue open to clean up unused items (resources?) during
deployment

**Comment by lhoang29** [comment]
What do you mean? These are resources that are completely unrelated to the DS that we created in our subscription for other purposes. Users won't get them after deployment.
