### ISSUE TITLE
Improvements to clarity of test drive UI

### ISSUE THREAD

**Issue by sidsen** [Microsoft/mwt-ds#20]
Some concrete-ish suggestions:

1. The experimental unit duration is confusing: if you're idle for a while or if you refresh the page for some other reason, events will be completed without your reward input. I think we should bring back the timer and set the default to 15 seconds (10 seconds is too short).

2. Related to the above, when the exp unit expires and you click thumbs up/down we are sending orphaned reward info. Instead, if we have a timer, we can force a ChooseAction refresh after the current decision's window expires.

3. Let's pick a fixed duration for updating all text values on the page (# training examples, model timestamp, graph update time, etc.). I think every 10 seconds is good.

4. Move "Success..." statement to the top. Move trainer and model messages below that and connect them somehow. For example, say "Online trainer OK. Total leaerned examples: XX (Last status update: [datetime])". Then perhaps on a separate line: "Latest model deployed at: [datetime]".

5. Where do we say that clicks get a reward of "1" and non-clicks a reward of "0"? I only see the keyboard shortcuts. Can we make this more explicit?

**Comment by lhoang29** [comment]
If we change the exp duration to 15 secs then how about we keep all other timer and delays on the page to 15 as well? Just makes it easier for us and users to diagnose the behavior.

**Comment by JohnLangford** [comment]
I discussed with Sid.  I think we agree to not introduce the timer and instead refresh the image at the end of the experimental duration.   I also think we should stick with a 10 second experimental unit duration because longer times make the learning seem to not be working.

**Comment by eisber** [comment]
We have been at this point in the past and removed it as it will lead to a graph that shows performance degradation just as the browser is kept open. Did you consider this?

**Comment by JohnLangford** [comment]
Good point.  Let's just stick with what we have rather than refreshing the image.

**Comment by sidsen** [comment]
Spoke to John. Let's keep the last article in play while the user is idle so that the metrics don't decline. However, is it possible to say "Event expired" instead of "Success" when the user clicks thumbs up/down on a stale decision?

**Comment by eisber** [comment]
We can do a client side timestamp compared, but you're aware that this won't be 100% correct as we don't know the actual timestamp of EventHub.

**Comment by lhoang29** [comment]
If we show the Event Expired after the same amount as the EXP duration, it should always be true yes?

**Comment by eisber** [comment]
do you have a consistent clock? we don't know the queue status. It probably won't matter for the demo

**Comment by lhoang29** [comment]
true, and yes probably won't matter here.

**Comment by lhoang29** [comment]
for (5), I'm going to add more info to the wiki
