### ISSUE TITLE
Improvements to clarity of test drive plot

### ISSUE THREAD

**Issue by sidsen** [Microsoft/mwt-ds#21]
Some concrete-ish suggestions:

1. "Show results for the past" doesn't make sense. I expect to see an x-axis that spans exactly that time. We need to somehow convey that this is a sliding (tumbling?) window computation. We should say something like: "Data points are updated every XX. Each data point reflects data collected from a trailing window of YY". Then we might want to put a link to ASA's tumbling window definition.

2. Something to consider: we might just set the window to 6days or whatever the maximum is and not give the user the option to change it.

**Comment by eisber** [comment]
The window type is called hopping in Azure Stream Analytics terminology…

**Comment by sidsen** [comment]
Let's address point 1 but punt on point 2 above. We could write "Consider data from the last XX". You could even throw in the word "trailing" in there.

**Comment by lhoang29** [comment]
Do we have a thread/issue somewhere to remove the selectable option and default to 6d?
