### ISSUE TITLE
Empty model detected, skipping model update. (with softmax explorer)

### ISSUE THREAD

**Issue by ashudeep** [Microsoft/mwt-ds#22]
![image](https://cloud.githubusercontent.com/assets/2232098/16596041/165d56e6-42c0-11e6-9dce-775cd2cdf069.png)

VW arguments I use are: --cb_explore_adf --cb_type dr --softmax --lambda 10 -q ui
When I change the arguments to: --cb_explore_adf --cb_type dr --softmax --lambda 10
It again shows the same for different runs on the same deployment and waiting for minutes for the model to be learnt.

When I try to replicate it for the same simulation with the epsilon greedy setting i.e. VW params: --cb_explore_adf --epsilon 0.2 --cb_type dr -q ui

Seems like the softmax explorer doesn't work. I will also be trying the other exploration strategies that work with adf.

**Comment by eisber** [comment]
Empty model detected is an expected error message.
How do you know that softmax is not working?

**Comment by eisber** [comment]
Do you see any exceptions in AppInsights? Do you see any “model update” messages in AppInsights?

**Comment by ashudeep** [comment]
No exceptions. No model update messages too.
However, the following traces are present. I didn't update any parameters between the two runs.
![image](https://cloud.githubusercontent.com/assets/2232098/16624947/b77dac78-4370-11e6-8289-dc36cd16f96b.png)

**Comment by ashudeep** [comment]
I will try to replicate on a new deployment and post it soon.

**Comment by lhoang29** [comment]
@ashudeep, I assume you got over this problem? If so please close this issue
