### ISSUE TITLE
wrong example count

### ISSUE THREAD

**Issue by danmelamed** [Microsoft/mwt-ds#26]
In dmdp8, the "total learned examples" was 1 before I clicked anything.  It climbed to 2 after a page refresh.  This might be related to the issue the Kevin Gao reported in his email.

**Comment by sidsen** [comment]
I believe this is expected behavior. Basically, if you don't click anything within 10 seconds the datapoint will be completed with no reward. The same thing will occur after a browser refresh.

Issue #20 addresses this confusion, I believe, so we could consider closing this and citing that issue.

**Comment by danmelamed** [comment]
We can have 0 reward after a time-out, or 0 reward for clicking the “no-click” button, but I think having both would confuse people.

**Comment by eisber** [comment]
The “no-click” button exists to allow the game to be played faster.

**Comment by sidsen** [comment]
This issue will be resolved by addressing issue #20, which says to automatically refresh the article when the exp duration expires, so users aren't clicking on a stale decision.
