### ISSUE TITLE
EventHub deployment error

### ISSUE THREAD

**Issue by danmelamed** [Microsoft/mwt-ds#28]
All event hubs failed to deploy in dmdp4, which differs from past deployments in that I bumped up the MB/s param to 20.  Audit log revealed the following:

    "properties": {
        "message Time": "7/1/2016 9:03:33 PM UTC",
        "error": "Exceeded the maximum number of allowed receivers per partition in a consumer group which is 5 TrackingId:e460a788-e7ce-4fff-ad6d-9ebb6a1991f3_B32, SystemTracker:sb-633gnx76jn2q2:eventhub:eval~32766, Timestamp:7/1/2016 9:03:27 PM Reference:98a61183-4639-4a2c-a80c-2730936e8673, TrackingId:3aaeaca7-1fb9-44b7-85ab-d6febdd18650_B32, SystemTracker:sb-633gnx76jn2q2:eventhub:eval~32766|$default, Timestamp:7/1/2016 9:03:27 PM\r\n",
        "message": "EventHubBasedInputQuotaExceededError errors are occuring too rapidly. They are being suppressed temporarily",
        "type": "EventHubBasedInputQuotaExceededError",
        "correlation ID": "da94edf7-a970-48f3-8a1d-21905c46eea8"

**Comment by eisber** [comment]
Can you try 10 too?

**Comment by danmelamed** [comment]
OK

**Comment by danmelamed** [comment]
10 works OK, but I got 2 more failures with 20

**Comment by eisber** [comment]
15? It’s weird since EventHub is not created at all…

**Comment by danmelamed** [comment]
Lowered max MB/s to 16 in 2011059.
