### ISSUE TITLE
API test drive UI corrections

### ISSUE THREAD

**Issue by sidsen** [Microsoft/mwt-ds#30]
- The x-axis for all window sizes looked consistent except for the 1m window size. Can we in general make the plot axis ranges consistent no matter what window size you use?
- The font size for “Success…” and “Trainer..” seem to have decreased – can we increase them. Same goes for “Each data point…” and “Graph updated at…”.
- We need more space between the drop down box and “Each data point”. Also replace “Window Size” -> “Window size” to be consistent with other drop down.
- Unbold the window time as well as the “Graph updated” sentence.
- “Each data point reflects evaluation result averaged over a hopping window of size 1h.” -> “Each data point is computed over a hopping window of size 1h”.
- “Observered” is misspelled. Also, I don’t understand what “Observed” and “Counterfactual Policy” mean. Why is Counterfactual the only one with “Policy”?

**Comment by eisber** [comment]
observed: #9

**Comment by lhoang29** [comment]
@sidsen: some of these changes are already done, did you do them yourselves earlier? If so let me know which ones I should fix so we don't duplicate work.

**Comment by lhoang29** [comment]
linking some commits that fix these: c2a689859b15c10f7870c46f0d62550e32cf2d05, 3987aa740eadb95133d4606f4c78fc7f2a95fb91, d83ee5248d410732fce4f0d07ca40eb74b266980

**Comment by lhoang29** [comment]
Everything should be fixed. For the first item regarding x-axis, I don't see this, the plot range seems consistent across different window sizes. @sidsen can you double check? if that's true we can close the issue

**Comment by sidsen** [comment]
Let me try to repro that item and I'll get back to you. My portal is
painfully slow again for some reason.

Sid

**Comment by sidsen** [comment]
Based on our meeting today:

1. Let's change the labels of the plot lines:
- Current policy (actual)
- Current policy (predicted)
- AI article (predicted)
- Federal Reserve article (predicted)
I may have messed up the article names.

2. Also make sure that common deployment failures (Conflict in name, Write sourcecontrols, etc.) are clearly called out in the FAQ/troubleshooting. Tell users these are known Azure issues; please retry your deployment.

3. John/Alekh propposed self-normalized IPS estimator instead of IPS to reduce variance.

**Comment by lhoang29** [comment]
Everything should be fixed by me & Markus today. The relevant commits are cd8d6934be02af716a0926611a797d0a19604257, 2a75189438c0ee684477579028ebf97a43ac5b3d and 58e6a573708fba356a46332ac8ddd23b8b7c5ac0
