### ISSUE TITLE
Comments on Deploy-DS Wiki page

### ISSUE THREAD

**Issue by slivkins** [Microsoft/mwt-ds#31]
A few comments re https://github.com/Microsoft/mwt-ds/wiki/Deploy-a-Decision-Service. (but I'd rather not unilaterally decide on the changes.)

•	“blade”: azure-specific jargon? Replace with “panel”?
•	“tooltip button” -> “tooltip button (i)” (i.e., add that symbol)
•	Comment that in the “create new” option, the required line is a name. Maybe also suggest a good naming scheme if one is trying multiple deployments?
•	In the “legal terms”, the “accept” button is called “purchase”, which may be confusing to some. So perhaps comment that if your subscription is free, clicking “purchase” will not actually spend money?
•	Since not all locations seem to work, maybe advice to use US only locations?

**Comment by eisber** [comment]
I’d stick with “blade” as it seems official/public lingo: https://azure.microsoft.com/en-us/documentation/articles/azure-portal-overview/#how-to-customize-a-resource-blade

@ locations: this is subscription dependent. Not sure if e.g. European subscriptions work any better in the US?

**Comment by danmelamed** [comment]
All your suggestions except one sound good to me.  So now it’s not unilateral, and you can go ahead and make those changes ;)

The only one that’s problematic is the issue of locations/regions.  The one(s) that work(s) is subscription-dependent, as explained in the Troubleshooting Guide. (About to be merged with the FAQ, as Sid suggested.) I suggest you just point them there for more info.

Dan

**Comment by lhoang29** [comment]
Location question is related to #13

**Comment by slivkins** [comment]
@danmelamed : ok, I'll make the edits later tonight.

**Comment by slivkins** [comment]
@locations: I understand it is a general issue that locations must somehow match my subscription. But I have no idea which location I should choose, given my subscription (MWT Decision Support Test (pauloka)). Is there some way to find out? then would be good to put that into the FAQs.

**Comment by lhoang29** [comment]
Good point, I'll update the wiki. One way to go about this is to try creating a classic cloud service manually and see whether Azure allows it.

**Comment by slivkins** [comment]
Did the edits on the Wiki.
