### ISSUE TITLE
Comments on the "parameters" blade

### ISSUE THREAD

**Issue by slivkins** [Microsoft/mwt-ds#32]
Going one by one:

**Vowpal Wabbit Switches:**

-  is it switches (as in the title) or flags (as in explanation)? Let’s be consistent. 

- Maybe add “If not sure, go with the defaults” in explanation?

- We can put a cheat sheet in the explanation, so why not?

**Experimental unit duration**

- Reword explanation: “Max allowed #seconds to observe the reward after the decision is recorded.”

**Initial exploration epsilon**  Sounds weird. Suggested rewording:
- Title: “Initial exploration probability”

- Explanation: Probability of exploration before the first model is trained.

**MB/S** Change to "Bandwidth required (MB/s)"

**Model update interval** Title suggests it is in time units, but explanation says it is in #examples. So which one is it? If it can be either, explanation should be reworded.

**Comment by eisber** [comment]
@ Model update interval: both are supported. 0:0:5 -> time, 100 -> count

**Comment by danmelamed** [comment]
fixed

**Comment by slivkins** [comment]
@danmelamed Thanks. a few remaining things (minor).

**Expt unit duration** Imprecise explanation, it seems: Isn't it the time interval to _wait_ for report? (I mean, the report can happen earlier). Moreover, the time interval starts after the decision is __reported__, rather than after the decision is made. Am I missing smth?

**Model update interval** 
example count -> #examples
front end model updates -> model updates on the front end

**Comment by danmelamed** [comment]
Fixed.
