### ISSUE TITLE
Add tooltip buttons to the "custom deployment" blade?

### ISSUE THREAD

**Issue by slivkins** [Microsoft/mwt-ds#33]
Can we do that? Guidance via tooltips seems more effective than [only] via tutorial.

**Comment by lhoang29** [comment]
I don't think this is possible. We can only add descriptions to parameters which show up as tooltips (we don't even control the parameter tooltips either).

**Comment by slivkins** [comment]
@lhoang29 What do you mean, "we don't even control the parameter tooltips"? We edit the text there. Do you mean, we cannot control where the tooltips are placed?

**Comment by lhoang29** [comment]
Yes, we don't control the actual tooltips, just the text that goes inside. There's nothing like this for the entire blade to my knowledge

**Comment by slivkins** [comment]
Got it, thanks!
