### ISSUE TITLE
Online trainer failing to deploy on "US East" location

### ISSUE THREAD

**Issue by slivkins** [Microsoft/mwt-ds#34]
... with subscription “MWT Decision Support Test (pauloka)”.

... with error message of the form:
Unable to create domain name 'trainer-XXX': 'The location constraint is not valid'

... consistently: tried 4 times.

**Comment by lhoang29** [comment]
Yes, it's because the subscription you are using does not support the East US location. The solution is to try Central US or open a ticket in Azure to request for more access. Closing as duplicate of #13.
