### ISSUE TITLE
Misleading message

### ISSUE THREAD

**Issue by JohnLangford** [Microsoft/mwt-ds#37]
When you deploy the decision service then, wait a long time, then go to the API test drive page it says: "Please wait as...".   A polite person will wait resulting in nothing getting done.

**Comment by lhoang29** [comment]
Do you mean the "Please wait as trainer has not started yet" message? It should update fairly quickly (~ couple seconds at most) once it polls the trainer's status. If it helps, we can change it to "Checking trainer status".

**Comment by JohnLangford** [comment]
It does _not_ update quickly.   It did not update after hours of waiting.  Something which does not suggest waiting, which is the wrong thing to do, seems much better.

-John

**Comment by lhoang29** [comment]
In that case, it seems the bug is in message not updating rather than the message itself. I'll take a look to see if this still repros.

**Comment by lhoang29** [comment]
I can't repro this using 2 deployments from this morning, can you retry?

**Comment by lhoang29** [comment]
Going to close this as I cannot repro it anymore
