### ISSUE TITLE
nightly build with nuget failing

### ISSUE THREAD

**Issue by danmelamed** [Microsoft/mwt-ds#38]
It says "partial success" and shows an orange checkmark, but if you drill down, you'll see it actually fails to complete.  E.g., https://vowpalwabbit.visualstudio.com/Vowpal%20Wabbit/_build?_a=summary&buildId=486

The (first) specific error is like 
2016-07-08T19:16:11.4768700Z ##[error]Failed to process request. 'A package with id 'Microsoft.Research.MultiWorldTesting.ClientLibrary' and version '2.0.0.2' already exists and cannot be modified.'.

**Comment by eisber** [comment]
linked to the 2nd build

**Comment by danmelamed** [comment]
Not sure what you mean by "2nd".  The most recent build seems to have the same issue.

**Comment by eisber** [comment]
There are 2 build definitions. “Decision Service with nuget” and “Decision Service”. I updated the link on the README (which user won’t be able to access anyway as they’re not on the access list)

Markus

**Comment by danmelamed** [comment]
Clarification for future reference: The 2nd build that includes the nuget update achieves its objective despite only partial completion.  Forcing full completion would achieve nothing more.
