### ISSUE TITLE
ClientDecisionServiceSample Exceptions

### ISSUE THREAD

**Issue by ErikOmberg** [Microsoft/mwt-ds#41]
I spun up the Azure resources and got the API tutorial working. Next, I tried to run the ClientDecisionServiceSample examples. They gave me exceptions.

1) Easy fix - I put a constructor on UserContext, so that Features wasn't null in the Sample.cs run.
        public UserContext()
        {
            Features = new Dictionary<string, float>();
        }

2) Next, VWExplorer.cs was throwing exceptions in MapContext that I didn't yet figure out. If I had developerMode=true, then the exception happens on the Trace line. If developerMode=false, the vw.Predict call has this exception:

![image](https://cloud.githubusercontent.com/assets/8632110/16751974/30822046-47a3-11e6-8edf-fb7bb0bc2816.png)

Notes:
1) I think I set my SettingsBlobUri correct.
2) I saw the code comments about ClientDecisionServiceSample needing --cb_explore 10 eventhough the default Azure deploy uses --cb_explore 2. I deployed both ways, and had this same problem. 

Last question: Is --cb_explore really fixed at deploy time? I saw that I could change the VW settings in the Azure instance, but I wasn't sure if they'd take effect or not.

**Comment by lhoang29** [comment]
Thanks for trying out the deployment! The null exception should be fixed now (not sure why/when the constructor went missing). Yes you need to set --cb_explore 10 for the sample to work properly. You could change the VW settings in the management center. We'll look into the MapContext exception.

**Comment by ErikOmberg** [comment]
Thank you for the fix. It works great.
