### ISSUE TITLE
possibly new type of deployment failure

### ISSUE THREAD

**Issue by danmelamed** [Microsoft/mwt-ds#42]
PDNE-dp-1 reports the MC as failing to deploy.  Drilling down in the portal reveals no specific cause of failure.  The audit logs report errors for Write Sourcecontrols and Write Deployments, but again with no specific reason that I can see.

**Comment by alekh** [comment]
This sounds like potentially same one that I found a few days back, and had
informed Louie/Markus about it.

Alekh

**Comment by lhoang29** [comment]
If I recall correctly, this was not an issue we control and the fix is in Aug timeframe.

**Comment by danmelamed** [comment]
duplicate of #8
