### ISSUE TITLE
Can we have “pin to dashboard” checked by default?

### ISSUE THREAD

**Issue by slivkins** [Microsoft/mwt-ds#49]
On DS deployment blade, can we have “pin to dashboard” checked by default? Assuming this is what we'd like people to do.

**Comment by eisber** [comment]
No. Azure team already declined. There were lots of discussion and the majority of users prefers it to be not checked.

Markus

On Jul 15, 2016, at 4:33 PM, slivkins <notifications@github.com<mailto:notifications@github.com>> wrote:


On DS deployment blade, can we have “pin to dashboard” checked by default? Assuming this is what we'd like people to do.
