### ISSUE TITLE
Broken links in MC

### ISSUE THREAD

**Issue by slivkins** [Microsoft/mwt-ds#50]
- Entry page, the link for “How do I find my password” does not go to an existing Wiki page.
- In MC/settings, links next to: 
     - Application Insights (I get “error retrieving data”)
     - ASA policy evaluation (I get “This asset was not found, it may have been deleted”)
     - ASA join server (I get “This asset was not found, it may have been deleted”)

**Comment by lhoang29** [comment]
ah, good catch
