### ISSUE TITLE
Misleading claim

### ISSUE THREAD

**Issue by JohnLangford** [Microsoft/mwt-ds#7]
"Latest model obtained at: December 31st 0000, 7:00:00pm".  Can we make this say something a bit more plausible?

**Comment by danmelamed** [comment]
This was marked closed 5h ago, but the problem persists, so I'm reopening it.

**Comment by lhoang29** [comment]
Can you try again? Apparently I missed something from the last fix.

**Comment by danmelamed** [comment]
Still broken.  See dmdp8.

**Comment by JohnLangford** [comment]
Still not working.
