### ISSUE TITLE
Use TRY_CAST for reward

### ISSUE THREAD

**Issue by eisber** [Microsoft/mwt-ds#70]
TRY_CAST returns NULL if the given type doesn't match. By using it with float type we should be able to strip out other rewards that should be logged as aux data.
Still we need to embed those rewards into the example as _reward to have them in the joined data

**Comment by lhoang29** [comment]
fixed in fa8c8c0f35c08ca6949ad9e46224d88e23b758b9?

**Comment by eisber** [comment]
Looks good.
