### ISSUE TITLE
Deployment failure

### ISSUE THREAD

**Issue by JohnLangford** [Microsoft/mwt-ds#8]
For the management center, I got the following fail in foo-2:

{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "Conflict",
            "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}

**Comment by eisber** [comment]
Following up internally.

**Comment by eisber** [comment]
This is a transient issue

**Comment by lhoang29** [comment]
The ARM team confirmed that this is one of their issues which will be fixed in Aug timeframe. In the meantime, Markus found that it doesn't happen too often (3/23 deployments) so it's not an urgent problem.

**Comment by danmelamed** [comment]
3 / 23 = 13%!  Since we have no control over the UI, is there anything we can do to prevent confused users from giving up?

**Comment by lhoang29** [comment]
I think we can only do a good job at informing them via our wiki and doc links for now.
