### ISSUE TITLE
Better names for "Online Policy" and "Offline Policy"

### ISSUE THREAD

**Issue by JohnLangford** [Microsoft/mwt-ds#9]
These names don't describe things very well.  Maybe "Observed" and "Counterfactual Policy"?  Or something else more descriptive.

**Comment by eisber** [comment]
Observed = deployed
Counterfactual Policy = currently learned policy
?

+1 for observed, not so sure on counterfactual.

**Comment by lhoang29** [comment]
Hmm, I like "Deployed" slightly better than "Observed" although both are clear enough. "Counterfactual" also seems a bit cryptic to me, what about we just call it "Trainer Policy"? Then perhaps:
1. "Deployed Policy" vs "Trainer Policy". Or:
2. "Client Policy" vs "Trainer Policy"

**Comment by danmelamed** [comment]
Whatever terms we use in the graph legend, I strongly suggest adding a brief explanation below the graph.  There is just not enough room inside the graph to unpack those terms enough for non-experts.

Dan
